version: '3.9'

services:
  backend:
    build: ./
    command: ./go-people-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=88888888
      - POSTGRES_DB=people
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=88888888
      - POSTGRES_DB=people
    ports:
      - 5432:5432